service: "default"

runtime: "java21"
env: "flex"

handlers:
  - url: "/.*"
    script: "this field is required, but ignored"

manual_scaling:
  instances: 1

health_check:
  enable_health_check: false

# env_variables:
#  ENCRYPT_KEY: "your_encryption_key_here"
